cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('', views.cart_summary, name="cart_summary"),
	path('add/', views.cart_add, name="cart_add"),
	path('delete/', views.cart_delete, name="cart_delete"),
	path('update/', views.cart_update, name="cart_update"),
]

ecom/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static
from . views import payment_completed_view
from . views import payment_failed_view


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('cart/', include('cart.urls')),
    path('checkout/', include('checkout.urls')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('payment-completed/', payment_completed_view, name="payment-completed"),
    path('payment-failed/', payment_failed_view, name="payment-failed"),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register_user, name='register'),
    path('update_password/', views.update_password, name='update_password'),
    path('update_user/', views.update_user, name='update_user'),
    path('update_info/', views.update_info, name='update_info'),
    path('product/<int:pk>', views.product, name='product'),
    path('category/<str:foo>', views.category, name='category'),
    path('category_summary/', views.category_summary, name='category_summary'),
]

store/models.py
from django.db import models
import datetime
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django_countries.fields import CountryField


# Create Customer Profile
class Profile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	date_modified = models.DateTimeField(User, auto_now=True)
	phone = models.CharField(max_length=20, blank=True)
	address1 = models.CharField(max_length=200, blank=True)
	address2 = models.CharField(max_length=200, blank=True)
	city = models.CharField(max_length=200, blank=True)
	state = models.CharField(max_length=200, blank=True)
	zipcode = models.CharField(max_length=200, blank=True)
	country = models.CharField(max_length=200, blank=True)

	def __str__(self):
		return self.user.username

# Create a user Profile by default when user signs up
def create_profile(sender, instance, created, **kwargs):
	if created:
		user_profile = Profile(user=instance)
		user_profile.save()

# Automate the profile thing
post_save.connect(create_profile, sender=User)







# Categories of Products
class Category(models.Model):
	name = models.CharField(max_length=50)

	def __str__(self):
		return self.name

	class Meta:
		verbose_name_plural = 'categories'


# Customers
class Customer(models.Model):
	first_name = models.CharField(max_length=50)
	last_name = models.CharField(max_length=50)
	phone = models.CharField(max_length=10)
	email = models.EmailField(max_length=100)
	password = models.CharField(max_length=100)


	def __str__(self):
		return f'{self.first_name} {self.last_name}'



# All of our Products
class Product(models.Model):
	name = models.CharField(max_length=100)
	price = models.DecimalField(default=0, decimal_places=2, max_digits=6)
	category = models.ForeignKey(Category, on_delete=models.CASCADE, default=1)
	description = models.TextField(default='', blank=True, null=True)
	image = models.ImageField(upload_to='uploads/product/')
	# Add Sale Stuff
	is_sale = models.BooleanField(default=False)
	sale_price = models.DecimalField(default=0, decimal_places=2, max_digits=6)

	def __str__(self):
		return self.name


# Customer Orders
class Order(models.Model):
	product = models.ForeignKey(Product, on_delete=models.CASCADE)
	customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
	quantity = models.IntegerField(default=1)
	address = models.CharField(max_length=100, default='', blank=True)
	phone = models.CharField(max_length=20, default='', blank=True)
	date = models.DateField(default=datetime.datetime.today)
	status = models.BooleanField(default=False)

	def __str__(self):
		return self.product

# Customer Address
class CheckoutAddress(models.Model):
    customer =  models.ForeignKey(Customer, on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)

    def __str__(self):
       return f'{self.customer.first_name} {self.customer.last_name}'

store/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, SetPasswordForm
from django import forms
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget
from .models import Profile


class UserInfoForm(forms.ModelForm):
	phone = forms.CharField(label="", widget=forms.TextInput(attrs={
		'class':'form-control',
	    'placeholder':'Phone'}), required=False)
	
	address1 = forms.CharField(label="", widget=forms.TextInput(attrs={
		'class':'form-control', 
		'placeholder':'Address 1'}), required=False)
	
	address2 = forms.CharField(label="", widget=forms.TextInput(attrs={
		'class':'form-control', 
		'placeholder':'Address 2'}), required=False)
	
	city = forms.CharField(label="", widget=forms.TextInput(attrs={
		'class':'form-control', 
		'placeholder':'City'}), required=False)
	
	state = forms.CharField(label="", widget=forms.TextInput(attrs={
		'class':'form-control', 
		'placeholder':'State'}), required=False)
	
	zipcode = forms.CharField(label="", widget=forms.TextInput(attrs={
		'class':'form-control', 
		'placeholder':'Zipcode'}), required=False)
	
	country = forms.CharField(label="", widget=forms.TextInput(attrs={
		'class':'form-control', 
		'placeholder':'Country'}), required=False)
	

	class Meta:
		model = Profile
		fields = ('phone', 'address1', 'address2', 'city', 'state', 'zipcode', 'country', )



from django import forms
from django.contrib.auth.forms import SetPasswordForm, PasswordChangeForm
from django.contrib.auth.models import User

class ChangePasswordForm(PasswordChangeForm):
    old_password = forms.CharField(
        label='',
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Old Password'}),
        help_text='<span class="form-text text-muted"><small>Enter your current password.</small></span>'
    )

    class Meta:
        model = User
        fields = ['old_password', 'new_password1', 'new_password2']

    def __init__(self, *args, **kwargs):
        super(ChangePasswordForm, self).__init__(*args, **kwargs)

        self.fields['new_password1'].widget.attrs['class'] = 'form-control'
        self.fields['new_password1'].widget.attrs['placeholder'] = 'New Password'
        self.fields['new_password1'].label = ''
        self.fields['new_password1'].help_text = '<ul class="form-text text-muted small"><li>Your password can\'t be too similar to your other personal information.</li><li>Your password must contain at least 8 characters.</li><li>Your password can\'t be a commonly used password.</li><li>Your password can\'t be entirely numeric.</li></ul>'

        self.fields['new_password2'].widget.attrs['class'] = 'form-control'
        self.fields['new_password2'].widget.attrs['placeholder'] = 'Confirm Password'
        self.fields['new_password2'].label = ''
        self.fields['new_password2'].help_text = '<span class="form-text text-muted"><small>Enter the same password as before, for verification.</small></span>'


class UpdateUserForm(UserChangeForm):
	# Hide Password stuff
	password = None
	# Get other fields
	email = forms.EmailField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Email Address'}), required=False)
	first_name = forms.CharField(label="", max_length=100, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'First Name'}), required=False)
	last_name = forms.CharField(label="", max_length=100, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Last Name'}), required=False)

	class Meta:
		model = User
		fields = ('username', 'first_name', 'last_name', 'email')

	def __init__(self, *args, **kwargs):
		super(UpdateUserForm, self).__init__(*args, **kwargs)

		self.fields['username'].widget.attrs['class'] = 'form-control'
		self.fields['username'].widget.attrs['placeholder'] = 'User Name'
		self.fields['username'].label = ''
		self.fields['username'].help_text = '<span class="form-text text-muted"><small>Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</small></span>'

		
class SignUpForm(UserCreationForm):
	email = forms.EmailField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Email Address'}))
	first_name = forms.CharField(label="", max_length=100, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'First Name'}))
	last_name = forms.CharField(label="", max_length=100, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Last Name'}))

	class Meta:
		model = User
		fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

	def __init__(self, *args, **kwargs):
		super(SignUpForm, self).__init__(*args, **kwargs)

		self.fields['username'].widget.attrs['class'] = 'form-control'
		self.fields['username'].widget.attrs['placeholder'] = 'User Name'
		self.fields['username'].label = ''
		self.fields['username'].help_text = '<span class="form-text text-muted"><small>Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</small></span>'

		self.fields['password1'].widget.attrs['class'] = 'form-control'
		self.fields['password1'].widget.attrs['placeholder'] = 'Password'
		self.fields['password1'].label = ''
		self.fields['password1'].help_text = '<ul class="form-text text-muted small"><li>Your password can\'t be too similar to your other personal information.</li><li>Your password must contain at least 8 characters.</li><li>Your password can\'t be a commonly used password.</li><li>Your password can\'t be entirely numeric.</li></ul>'

		self.fields['password2'].widget.attrs['class'] = 'form-control'
		self.fields['password2'].widget.attrs['placeholder'] = 'Confirm Password'
		self.fields['password2'].label = ''
		self.fields['password2'].help_text = '<span class="form-text text-muted"><small>Enter the same password as before, for verification.</small></span>'



PAYMENT = (
    ('S', 'Stripe'),
    ('P', 'PayPal')
)

class CheckoutForm(forms.Form):
    customer_firstname = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Your firstname'
    }))
    customer_lastname = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Your lastname'
    }))
	
    
    street_address = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': '1234 Main St'
    }))
    apartment_address = forms.CharField(required=False, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Apartment or suite'
    }))
    country = CountryField(blank_label='(select country)').formfield(widget=CountrySelectWidget(attrs={
        'class': 'form-control custom-select d-block w-100'
    }))
    zip = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control'
    }))
    customer_phone = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': '+212xxxxxxxxx'
    }))
    customer_email = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'example@examole.com'
    }))
    same_billing_address = forms.BooleanField(required=False)
    save_info = forms.BooleanField(required=False)
    payment_option = forms.ChoiceField(
        widget=forms.RadioSelect, choices=PAYMENT)
	

store/views.py
from django.shortcuts import render, redirect
from .models import Product, Category, Profile
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .forms import SignUpForm, UpdateUserForm, ChangePasswordForm, UserInfoForm
from django import forms


def update_info(request):
    if request.user.is_authenticated:
        current_user = Profile.objects.get(user=request.user)
        form = UserInfoForm(request.POST or None, instance=current_user)

        if form.is_valid():
            form.save()

            messages.success(request, "Your Info Has Been Updated!!")
            return redirect('home')
        return render(request, "update_info.html", {'form': form})
    else:
        messages.success(request, "You Must Be Logged In To Access That Page!!")
        return redirect('home')


def update_password(request):
	if request.user.is_authenticated:
		current_user = request.user
		# Did they fill out the form
		if request.method  == 'POST':
			form = ChangePasswordForm(current_user, request.POST)
			# Is the form valid
			if form.is_valid():
				form.save()
				messages.success(request, "Your Password Has Been Updated...")
				login(request, current_user)
				return redirect('update_user')
			else:
				for error in list(form.errors.values()):
					messages.error(request, error)
					return redirect('update_user')
		else:
			form = ChangePasswordForm(current_user)
			# return render(request, "update_password.html", {'form':form})
	else:
		messages.success(request, "You Must Be Logged In To View That Page...")
		return redirect('home')
def update_user(request):
    if request.user.is_authenticated:
        current_user = Profile.objects.get(user=request.user)
        user_form = UpdateUserForm(request.POST or None, instance=current_user.user)
        form = UserInfoForm(request.POST or None, instance=current_user)
        form_pass = ChangePasswordForm(current_user.user, request.POST)

        if user_form.is_valid():
            user_form.save()

            login(request, current_user.user)
            messages.success(request, "User Has Been Updated!!")
            return redirect('home')
        return render(request, "update_user.html", {'user_form': user_form, 'form': form, 'form_pass': form_pass})
    else:
        messages.success(request, "You Must Be Logged In To Access That Page!!")
        return redirect('home')


def category_summary(request):
	categories = Category.objects.all()
	return render(request, 'category_summary.html', {"categories":categories})	

def category(request, foo):
	# Replace Hyphens with Spaces
	foo = foo.replace('-', ' ')
	# Grab the category from the url
	try:
		# Look Up The Category
		category = Category.objects.get(name=foo)
		products = Product.objects.filter(category=category)
		return render(request, 'category.html', {'products':products, 'category':category})
	except:
		messages.success(request, ("That Category Doesn't Exist..."))
		return redirect('home')


def product(request,pk):
	product = Product.objects.get(id=pk)
	return render(request, 'product.html', {'product':product})

def home(request):
	products = Product.objects.all()
	return render(request, 'home.html', {'products':products})


def about(request):
	return render(request, 'about.html', {})	

def login_user(request):
	if request.method == "POST":
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(request, username=username, password=password)
		if user is not None:
			login(request, user)
			messages.success(request, ("You Have Been Logged In!"))
			return redirect('home')
		else:
			messages.success(request, ("There was an error, please try again..."))
			return redirect('login')

	else:
		return render(request, 'login.html', {})


def logout_user(request):
	logout(request)
	messages.success(request, ("You have been logged out...Thanks for stopping by..."))
	return redirect('home')



def register_user(request):
	form = SignUpForm()
	if request.method == "POST":
		form = SignUpForm(request.POST)
		if form.is_valid():
			form.save()
			username = form.cleaned_data['username']
			password = form.cleaned_data['password1']
			# log in user
			user = authenticate(username=username, password=password)
			login(request, user)
			messages.success(request, ("Username Created - Please Fill Out Your User Info Below..."))
			return redirect('update_info')
		else:
			messages.success(request, ("Whoops! There was a problem Registering, please try again..."))
			return redirect('register')
	else:
		return render(request, 'register.html', {'form':form})

store/templates/about.html
{% extends 'base.html' %}
{% block content %}

<!-- Header-->
        <header class="py-5 bg-secondary">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-black">
                    <h1 class="display-4 fw-bolder">About Us...</h1>
                    <p class="lead fw-normal text-black-50 mb-0">Welcome to our Ecommerce Project</p>
                </div>
            </div>
        </header>

        <div class="container">
        	<div class="row">
        		<center>
        			<div class="col-8">
        				<br/><br/>
<p align="justify">
Welcome to our web application! We are Hatim Touijar, Mounia Dahbi, Souhaila Morabit and Mohamed Chaouki Touzani, a passionate team dedicated to bringing you the latest and greatest electronic devices. We have come together with a shared vision: to provide a seamless shopping experience for tech enthusiasts everywhere. Our commitment to quality, innovation, and customer satisfaction drives everything we do. Whether you're searching for the latest smartphones, fastest most powerful laptops, or the right gaming consoles for the right gaming experience, you can trust that each product existing in our platform has been carefully selected by our team. Join us on this journey as we strive to redefine the way you shop for electronics.
<br/><br/>
While this may be our first experience in developing a web application, our commitment to excellence and our thirst for learning and doing the best we can to impress you is keeping us forward every step of the way. Through collaboration, experimentation, and eternal pursuit of improvement, we've crafted a platform that we're proud to present to you. Join us as we continue to learn, grow, and innovate in the ever-evolving world of digital technology.
<br/><br/>

<strong>Anything You Want... WE HAVE, And if we Don't... Just say the MAGIC WORD and we'll get it for YOU.
  Because we are DSEF ELECTRONICS, And we Are here for your Electronic needs.</strong>
</p>
</p>
<br/><br/>
        			</div>
        		</center>
        	</div>
        </div>

{% endblock %}

store/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Django Ecommerce</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
        
    </head>
    <body>
        {% include 'navbar.html' %}
        {% if messages %}
            {% for message in messages %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  {{ message }}
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
            {% endfor %}
        {% endif %}
        
        {% block content %}
        {% endblock %}




        <!-- Footer-->
        <footer class="py-5 bg-secondary">
            <div class="container">
                <p class="m-0 text-center text-dark"style="font-weight: bold" >Copyright &copy; DSEF Electronics.</p>
            </div>
        </footer>
        

        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

store/templates/update_user.html
{% extends 'base.html' %}
{% comment %} {% load crispy_forms_tags %} {% endcomment %}
{% block content %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CodingDung | Profile Template</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>


<body id="prof">
    <div class="container light-style flex-grow-1 container-p-y">
        <h4 class="font-weight-bold py-3 mb-4">
            Account settings
        </h4>
        <div class="card overflow-hidden">
            <div class="row no-gutters row-bordered row-border-light">
                <div class="col-md-3 pt-0">
                    <div class="list-group list-group-flush account-settings-links">
                        <a class="list-group-item list-group-item-action active" data-toggle="list"
                            href="#account-general">General info</a>
                        <a class="list-group-item list-group-item-action" data-toggle="list"
                            href="#account-change-password">Change password</a>
                        <a class="list-group-item list-group-item-action" data-toggle="list" href="#account-info">Update
                            Shipping information
                        </a>
                    </div>
                </div>
                <div class="col-md-9">
                    <div class="tab-content">
                        <div class="tab-pane fade active show" id="account-general">

                            <hr class="border-light m-0">
                            <div class="card-body">
                                <h6 class="mb-4">General information :</h6>
                                <form method="POST" action="{% url 'update_user' %}">

                                    {% csrf_token %}

                                    <div class="row">
                                        <div class="col-md-6">
                                            <label for="{{ user_form.username.id_for_label }}">User Name:</label>
                                            {{ user_form.username }}
                                        </div>
                                        <div class="col-md-6">
                                            <label for="{{ user_form.first_name.id_for_label }}">First Name:</label>
                                            {{ user_form.first_name }}
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col-md-6">
                                            <label for="{{ user_form.last_name.id_for_label }}">Last Name:</label>
                                            {{ user_form.last_name }}
                                        </div>
                                        <div class="col-md-6">
                                            <label for="{{ user_form.email.id_for_label }}">Email Address:</label>
                                            {{ user_form.email }}
                                        </div>
                                    </div>
                                    <br>
                                    <button type="submit" class="btn btn-secondary" style="background-color: #007bff;">
                                        Update Profile
                                    </button>
                                </form>

                            </div>
                        </div>
                        <div class="tab-pane fade" id="account-change-password">
                            <div class="card-body pb-2">
                                <h6 class="mb-4">Change Password :</h6>

                                <form method="POST" action="{% url 'update_password' %}">
                                    {% csrf_token %}


                                    <div class="row">
                                        <div class="col-md-6">
                                            <label for="id_old_password">Old Password:</label>
                                            <input type="password" name="old_password" id="id_old_password"
                                                class="form-control" required>
                                        </div>

                                    </div>

                                    <div class="row">
                                        <div class="col-md-6">
                                            <label for="id_new_password1">New Password:</label>
                                            <input type="password" name="new_password1" id="id_new_password1"
                                                class="form-control" required>
                                        </div>


                                    </div>

                                    <div class="row">
                                        <div class="col-md-6">
                                            <label for="id_new_password2">Confirm Password:</label>
                                            <input type="password" name="new_password2" id="id_new_password2"
                                                class="form-control" required>
                                        </div>

                                    </div>



                                    <br /><br />
                                    <button type="submit" class="btn btn-secondary" style="background-color: #007bff;">
                                        Update Password
                                    </button>
                                </form>


                            </div>
                        </div>
                        <div class="tab-pane fade" id="account-info">
                            <!-- My shipping section -->
                            <div class="card-body pb-2">
                                <h6 class="mb-4">Update your Shipping information :</h6>
                                <form method="POST" class="card-body" action="{% url 'update_info' %}">
                                    {% csrf_token %}
                                  
                                    <!--address-->
                                    <div class="md-form mb-5">
                                      <label for="address" class="">Address</label>
                                      {{ form.address1 }}
                                    </div>
                                  
                                    <!--address-2-->
                                    <div class="md-form mb-5">
                                      <label for="address-2" class="">Address 2 (optional)</label>
                                      {{ form.address2 }}
                                    </div>
                                  
                                    <!--Grid row-->
                                    <div class="row mb-5">
                                  
                                      <!--Grid column-->
                                      <div class="col-lg-6 col-md-12 mb-6">
                                        <label for="country">Country</label>
                                        {{ form.country }}
                                      </div>
                                      <!--Grid column-->
                                  
                                      <!--Grid column-->
                                      <div class="col-lg-6 col-md-12 mb-6">
                                        <label for="country">City</label>
                                        {{ form.city }}
                                      </div>
                                      
                                      <!--Grid column-->
                                  
                                    </div>
                                    <!--Grid row-->
                                  
                                    <!--Phone and Email-->
                                    <div class="row">
                                  
                                      <!--Grid column-->
                                      <div class="col-lg-6 col-md-12 mb-6">
                                        <label for="customer_phone">Phone</label>
                                        {{ form.phone }}
                                      </div>
                                      <!--Grid column-->
                                  
                                      <!--Grid column-->
                                      <div class="col-lg-6 col-md-12 mb-6">
                                  
                                        <label for="zip">Zip</label>
                                        {{ form.zipcode }}
                                        <div class="invalid-feedback">
                                          Zip code required.
                                        </div>
                                  
                                      </div>
                                      <!--Grid column-->
                                  
                                    </div>
                                    <br /><br />
                                    <button type="submit" class="btn btn-secondary" style="background-color: #007bff;">
                                        Update Profile
                                    </button>
                                  </form>


                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/js/bootstrap.bundle.min.js"></script>
    <script type="text/javascript">
        function previewImage() {
            var input = document.getElementById('profileImageInput');
            var image = document.getElementById('profileImage');

            var file = input.files[0];
            var reader = new FileReader();

            reader.onload = function (e) {
                image.src = e.target.result;
            };

            reader.readAsDataURL(file);
        }
    </script>
</body>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>


{% endblock %}